# Generated by Django 4.1.5 on 2023-01-19 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transportador', '0002_rename_transportador_cadastro'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcoZero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=150)),
                ('lat_long', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='AreaDeCorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_marco_zero', models.IntegerField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transportador.marcozero')),
                ('transportador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transportador.cadastro')),
            ],
        ),
    ]
