# Generated by Django 4.1.5 on 2023-01-19 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transportador', '0004_alter_cadastro_cnpj_alter_cadastro_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areadecorte',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportador.marcozero'),
        ),
        migrations.AlterField(
            model_name='areadecorte',
            name='transportador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportador.cadastro'),
        ),
    ]
